### ISSUE TITLE
Failed to find Premain-Class manifest attribute ... spock-mockable

### ISSUE THREAD

**Issue by ThomHehl** [joke/spock-mockable#365]
Tried following directions. Got this issue: https://stackoverflow.com/questions/76190239/failed-to-find-premain-class-manifest-attribute-spock-mockable

**Comment by kriegaex** [comment]
@ThomHehl: I answered that question already in https://stackoverflow.com/a/76192456/1082681. I am not sure if it makes sense to cross-post everywhere. You even pointed to your question from comments in other StackOverflow questions.

@joke: That this bogus version number - see my answer on SO - is listed as the most recent one despite  its older timestamp, because it starts with "3", is unfortunate. How about opening an [OSSRH support ticket](https://issues.sonatype.org/projects/OSSRH/), pointing to my SO answer and explaining why this would be a rare and justified case to actually remove an artifact from Maven Central. The odd version number implies that the release was not on purpose anyway.

**Comment by joke** [comment]
@ThomHehl, @kriegaex 

thanks for reporting the issue. Nevertheless I'm opening a OSSRH support ticket.
Even though bogus that release has already been downloaded from maven central as well as the github maven package archive. Removing the release would break these builds.
